os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/98dae83d630ca15b65288a8f808eae3ec5cea313/swiftenv-install.sh)"
script:
- make test
