language: generic
sudo: required
dist: trusty
env:
- SWIFT_VERSION=$(cat .swift-version)
install:
- mkdir swift && curl https://swift.org/builds/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
script:
- env PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH make test
